name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   node-docker:
      runs-on: ubuntu-latest
      container:
       image: node:alpine:fermium-alpine3.15
      steps:
        - name: log node version
          run: |
            node -v
            cat /etc/os-release
